#pragma once
#define MAP_WIDTH 1400.0f
#define MAP_HEIGHT 750.0f

#define BT_TOUR_PLAYER	1
#define BT_TOUR_AI		2

#define ENTITY_MAX_HEALTH		100.0f
#define ENTITY_MAX_ARMOR		20.0f

#define ENTITY_ALLY 1
#define ENTITY_ENEMY 2
#define ENTITY_WHATEVER 3

#define NEUTRAL 0
#define ENEMY 1
#define ALLY 2

#define SQUAD_MAX_SIZE 15

#define MODEL_ORKS 0
#define MODEL_HUMANS 1
#define MODEL_NOMADS 2
#define MODEL_EVIL_HUMANS 3
#define MODEL_GOBLINS 4
#define MODEL_PLAYER 5
#define MODEL_BANDITS 6
#define MODEL_ANIMALS 7

#define MODEL_BUILDING 77

#define SHOP_ROTATION_TIMER 500

#define MAX_MELEE_STAT_PRICE 40f
#define MAX_RANGED_STAT_PRICE 40f
#define MAX_DEFENCE_STAT_PRICE 60f
#define MAX_BRAVERY_STAT_PRICE 40f
#define MAX_HP_STAT_PRICE 60f

#define ANIMATION_MELEE_ATACK	80
#define ANIMATION_RANGE_ATTACK	81
#define BASE_ENTITY_VALUE 50.0f;
#define MAX_MELEE_STAT_PRICE 40.0f
#define MAX_RANGED_STAT_PRICE 40.0f
#define MAX_DEFENCE_STAT_PRICE 60.0f
#define MAX_BRAVERY_STAT_PRICE 40.0f
#define MAX_HP_STAT_PRICE 60.0f